#ansible samples
- hosts: all
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Set timezone to EST
      command: timedatectl set-timezone US/Eastern
    
    - name: Create cloudcoe user in all servers
      user:
        name: cloudcoe1
        password: "{{ 'cloudcoe123' | password_hash('sha512') }}"
        state: present
        createhome: yes
    
    - name: Add cloudcoe1 to wheel group
      command: usermod -aG wheel cloudcoe1

    - name: Change PasswordAuthenticaion
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: '^PasswordAuthentication'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'
      #notify:
      #- restart sshd 

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted

    - name: Check OS version of the server
      command: cat /etc/redhat-release
      register: os_version

    - name: Copy OS name to text file
      delegate_to: localhost
      copy:
        content: "{{ os_version_stdout_lines | to_nice_json }}"
        dest: "/devops/aws/ansible/results/{{ inventory_hostname }}.txt"
    


      


        


