#Remove users in hosts
- name: Delete CloudCOE user
  hosts: servers
  tasks:
    - name: Delete CloudCOE
      ansible.builtin.user:
         name: CloudCOE
         state: "absent"
         remove: true
