#ansible samples
- hosts: all
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: set timezone to EST
      command: timedatectl set-timezone US/Eastern
    
    - name: create cloudcoe user in all servers
      user:
        name: cloudcoe
        password: "{{ 'cloudcoe123' | password_hash('sha512') }}"
        groups: wheel
        state: present
        createhome: yes
      
    - name: add cloudcoe user to sudoers files
      blockinfile:
        path: /etc/sudoers
        insertafter: 'root    ALL=(ALL)       ALL'
        block:  |
          cloudcoe  ALL=(ALL) NOPASSWD: ALL

        


