#ansible samples
- hosts: all
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: set timezone to EST
      command: timedatectl set-timezone US/Eastern
    
    - name: create cloudcoe user in all servers
      user:
        name: cloudcoe
        password: "{{ 'cloudcoe123' | password_hash('sha512') }}"
        state: present
        createhome: yes
    
    - name: add cloudcoe to wheel group
      command: usermod -aG wheel cloudcoe

    - name: add cloudcoe to sudoers
      ansible.builtin.copy:
        src: "{{ sudoers }}"
        dest: /etc/sudoers.d
        validate: /usr/sbin/visudo -csf %s
      #loop: "{{ sudoers }}"

      


        


