#install HTTPD using Ansible
- name: Create local admin to servers
  hosts: servers
  tasks:
     - name: Create CloudCOE user
       user:
         name: CloudCOE
         uid: 1040
         group: wheel

         

     