#ansible samples
- hosts: all
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: set timezone to EST
      command: timedatectl set-timezone US/Eastern
    
    - name: create cloudcoe user in all servers
      user:
        name: cloudcoe1
        password: "{{ 'cloudcoe123' | password_hash('sha512') }}"
        state: present
        createhome: yes
    
    - name: add cloudcoe to wheel group
      command: usermod -aG wheel cloudcoe1

    - name: change PasswordAuthenticaion
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: '^PasswordAuthentication'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'
      notify:
      - restart sshd 

    #- name: restart sshd service
    # command: systemctl restart sshd



      


        


