#ansible samples
- hosts: all
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Set timezone to EST
      command: timedatectl set-timezone US/Eastern
    
    - name: Create cloudcoe user in all servers
      user:
        name: cloudcoe1
        password: "{{ 'cloudcoe123' | password_hash('sha512') }}"
        state: present
        createhome: yes
    
    - name: Add cloudcoe1 to wheel group
      command: usermod -aG wheel cloudcoe1

    - name: Change PasswordAuthenticaion
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: '^PasswordAuthentication'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'
      #notify:
      #- restart sshd 

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted

    - name: Run yum update
      ansible.builtin.yum:
        name: '*'
        state: latest

    