#ansible samples
- hosts: all
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: set timezone to EST
      community.general.timezone:
        name: US/Eastern





