#ansible samples
- hosts: all
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: set timezone to EST
      command: timedatectl set-timezone US/Eastern
    
    - name: create cloudcoe user in all servers
      user:
        name: cloudcoe
        password: "{{ 'cloudcoe123' | password_hash('sha512') }}"
        state: present
        createhome: yes
    
    - name: add cloudcoe to wheel group
      command: usermod -aG wheel cloudcoe

    - name: change PasswordAuthenticaion
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: '^PasswordAuthentication'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'
      notify:
      - restart sshd 

    - name: check hostname of the server
      command: hostname

    - name: Create your local file on master node
      ansible.builtin.file:
        path: /devops/aws/ansible/hostname.txt
        owner: master
        group: master
        mode: '0644'
      delegate_to: localhost

    - name: Print output to file
      ansible.builtin.copy:
        content: "{{command_output.stdout}}"
        dest: /devops/aws/ansible/hostname.txt
      delegate_to: localhost

    


      


        


