#ansible samples
- become: true 
  hosts: all
  # vars_files:
  #   - ./roles/vars/main.yaml
  tasks:
    - name: Get hostname of slave
      command: hostname
      register: command_output
    - name: cat /etc/os-release
      command: cat redhat-release chdir=/etc

    - name: Create your local file on master node
      ansible.builtin.file:
        path: /home/cloudcoe/devops/aws/ansible/hostname.txt
        owner: cloudcoe
        group: cloudcoe
        mode: '0644'
        state: touch
      delegate_to: localhost

    - name: Print output to file
      ansible.builtin.copy:
        content: "{{command_output.stdout}}"
        dest: /home/cloudcoe/devops/aws/ansible/hostname.txt
      delegate_to: localhost